New SED coding style.
Use commands 'i' and 'a' instead of 's'.
Place the '[file...]' argument(s) last for POSIX SED.

diff --git a/makeall b/makeall
--- a/makeall
+++ b/makeall
@@ -71,13 +71,13 @@ fi
 
 if [ $? -eq 0 ] # Check return code from getopt
 then eval set -- $OPTS
-else echo "Failed to parse options." >&2; exit 1
+else echo 'Failed to parse options.' >&2; exit 1
 fi
 
 while true
 do
 	case "$1" in
-		-c | --changes ) CHANGES="-changes"; shift ;;
+		-c | --changes ) CHANGES='-changes'; shift ;;
 		-f | --files ) FILES="$2"; FILESELECT=true; shift 2 ;;
 		-h | --help ) usage; exit 0 ;;
 		-n | --new ) NEW=true; shift ;;
@@ -90,12 +90,14 @@ do
 	esac
 done
 
-CWEAVE="cweave -f +lX +bph"
-CTWILL="ctwill -f +lpdf +bph"
-HITEX="hitex --compress"
-PAX="pax -wvzf"
+CWEAVE='cweave -f +lX +bph'
+CTWILL='ctwill -f +lpdf +bph'
+HITEX='hitex --compress'
+PAX='pax -wvzf'
 EXT=pdf # default extension for 'knuth-pdf'
-SED_I="sed -i" # non-GNU-sed requires an extra '' argument for '-i' option.
+SED_I='sed -i' # non-GNU-sed requires an extra '' argument for '-i' option.
+# Prevent '#1)' from showing up in the PDF bookmarks/outlines:
+PURGE_OUTLINES='s/\\(\([0-9a-z]\)[0-9a-z]*)/\\9{\1}/g'
 WEAVE=weave
 XETEX=xetex
 
@@ -135,10 +137,9 @@ do
 
 	case $f in
 		vftovp ) # FIX: Sorting order of named sections
-			sed $KNUTHWARE/$f.web -e '/\\def\\(/d' \
-			-e 's/\\(\([0-9a-z]\)[0-9a-z]*)/\\9{\1}/g' \
-			-e 's/\(Compute the \)\(|activity\)/\1\\9{a}\2/' \
-			> $f.web ;;
+			sed -e 's/\(Compute the \)\(|activity\)/\1\\9{a}\2/' \
+				-e $PURGE_OUTLINES -e '/\\def\\(/d' \
+				$KNUTHWARE/$f.web > $f.web ;;
 
 		pdftex ) # Fix several 'Overfull \hbox'es
 			tie -m $f.web $f.web $LOCALSTUFF/$f.ch ;;
@@ -146,8 +147,7 @@ do
 		hitex | mp | mpost | mpmath* | mpstrings | tfmin )
 			# Beautifications for HiTeX and MetaPost
 			tie -m $f.w $f.w $LOCALSTUFF/$f.ch
-			$SED_I $f.w -e '/\\def\\(/d' \
-				-e 's/\\(\([0-9a-z]\)[0-9a-z]*)/\\9{\1}/g' ;;
+			$SED_I -e $PURGE_OUTLINES -e '/\\def\\(/d' $f.w ;;
 
 		weave | twill ) # Fix non-constant factor
 			if [ "$HITEX" = "$TEX" ] && [ ! -f weave.web ]
@@ -183,22 +183,21 @@ s/\(ump \)\(constants\)/\1\\(c)\2/
 s/\(ump \)\(enc\)/\1\\(e)\2/
 s/\(ump \)\(ML\)/\1\\(m)\2/
 FI
-				sed $KNUTHWARE/$f.web -f tex-nos.sed > $f.web
-				sed $KNUTHWARE/../../Work/texk/web2c/$f-final.ch \
-					-f tex-nos.sed > $f-final.ch
+				sed -f tex-nos.sed $KNUTHWARE/$f.web > $f.web
+				sed -f tex-nos.sed $KNUTHWARE/../../Work/texk/web2c/$f-final.ch > $f-final.ch
 				WEBINPUTS=.:$WEBINPUTS $WEAVE $f $f-final
 				rm -f tex-nos.sed ;;
 
 			# FIX: Sorting order of new @<Define...@> sections
 			vftovp ) WEBINPUTS=.:$WEBINPUTS $WEAVE $f $f
-				$SED_I $f.tex -e 's/\\(\([0-9a-z]\)[0-9a-z]*)/\\9{\1}/g' ;;
+				$SED_I -e $PURGE_OUTLINES $f.tex ;;
 
 			# all other WEB codes have singular changefiles
 			* ) $WEAVE $f $f ;;
 		esac
 
 		# only document changed modules/sections
-		$SED_I $f.tex -e '/\\let\\maybe/s/\\iftrue/\\iffalse/'
+		$SED_I -e '/\\let\\maybe/s/\\iftrue/\\iffalse/' $f.tex
 	else # -z $CHANGES
 		case $f in
 			ctwill ) # apply tons of editorial changes to 'ctwill.w'
@@ -231,41 +230,38 @@ FI
 		# timestamp on table-of-contents page or the first page
 		case $f in
 			bibtex | patgen | tangle | weave | twill )
-				$SED_I $f.tex -e 's/\\def\\title{/\\datecontentspage\n&/' ;; # }
+				$SED_I -e '/\\def\\title{/i\
+\\datecontentspage' $f.tex ;; # }
 
 			mf | tex | pdftex | xetex )
 				# amend '\N' redefinition for PDF outlines in
 				# Metafont and TeX (also pdfTeX and XeTeX)
 				# 'pwebmac' defines headers differently
 				cat > texmf-pdf.sed << 'FI'
-/\\def\\(/d
-s/\\(\([0-9a-z]\)[0-9a-z]*)/\\9{\1}/g
 s/\\outer\\def\\N.*{/&%/
-/\\outer\\def\\N/r texmf-pdf.patch1
+/\\outer\\def\\N/a\
+  \\ifpdf{\\makeoutlinetoks{[#2] #3}\\outlinedone}\\fi
 s/\\def\\rhead/\\gtitle=/
-/\\gtitle=/r texmf-pdf.patch2
-s/{\\the\\pageno}/&{\\the\\toksE}/
-/\\edef\\next/r texmf-pdf.patch3
-s/\\def\\title{/\\datethis\n\\emergencystretch=.1\\hsize\n&/
-FI
-				cat > texmf-pdf.patch1 << FI
-  \ifpdf{\makeoutlinetoks{[#2] #3}\outlinedone}\fi
-FI
-				cat > texmf-pdf.patch2 << FI
+/\\gtitle=/a\
   \\MN#1.\\vfill\\eject % begin starred section
+s/{\\the\\pageno}/&{\\the\\toksE}/
+/\\edef\\next/a\
+  \\ifpdflua\\relax\\else\
+  \\ifpdf\\special{pdf: outline 0 << /Title (\\the\\toksE) /Dest\
+    [ @thispage /FitH @ypos ] >>}\\fi\\fi
+/\\def\\title{/i\
+\\datethis\
+\\emergencystretch=.1\\hsize
 FI
-				cat > texmf-pdf.patch3 << FI
-  \ifpdflua\relax\else
-  \ifpdf\special{pdf: outline 0 << /Title (\the\toksE) /Dest
-    [ @thispage /FitH @ypos ] >>}\fi\fi
-FI
-				$SED_I $f.tex -f texmf-pdf.sed
-				rm -f texmf-pdf.* ;;
+				$SED_I -f texmf-pdf.sed -e $PURGE_OUTLINES \
+					-e '/\\def\\(/d' $f.tex
+				rm -f texmf-pdf.sed ;;
 
-			* ) $SED_I $f.tex -e '/\\def\\botofcontents/d' \
+			* ) $SED_I -e '/\\def\\botofcontents/d' \
 				-e 's/  \\centerline{\(\\hsize\)/\\def\\covernote{\1/' \
 				-e 's/\(Publishing Company.}}\)}/\1\n\\datecontentspage/' \
-				-e 's/\(Mathematical Society.}}\)}/\1\n\\datecontentspage/' ;;
+				-e 's/\(Mathematical Society.}}\)}/\1\n\\datecontentspage/' \
+				$f.tex ;;
 		esac
 	fi # $NEW
 
@@ -277,58 +273,79 @@ FI
 		# 'E' no longer free to be active character
 		# fix table-of-contents page for bibtex
 		# FIX: don't wait for Oren Patashnik.
-		bibtex ) $SED_I $f.tex -e 's/\\def\\titlepage{F}/\\titletrue/'
-			[ -z "$CHANGES" ] && $SED_I $f.tex -e "71,78d" ;;
+		bibtex ) $SED_I -e 's/\\def\\titlepage{F}/\\titletrue/' $f.tex
+			[ -z "$CHANGES" ] && $SED_I -e '71,78d' $f.tex ;;
 
 		# FIX: GFtoDVI uses 'Metafont' in a module name;
 		# this should appear correctly in the bookmarks, too.
-		gftodvi ) $NEW && $SED_I $f.tex \
-			-e 's/\\def\\(/\\ifpdf\\sanitizecommand\\MF{Metafont}\\fi\n\n&/' ;; # )
+		gftodvi ) $NEW && $SED_I -e '/\\def\\MF/a\
+\\ifpdf\\sanitizecommand\\MF{Metafont}\\fi' $f.tex ;;
 
 		# FIX: 'glue.web' obviously uses an old 'webmac.tex'.
-		glue ) $SED_I $f.tex -e 's/titlefalse/titletrue/' \
-			-e 's/\\def\\title{GLUE}/&\n\\pageno=\\contentspagenumber \\advance\\pageno by1\\relax/' ;;
+		glue ) $SED_I -e 's/titlefalse/titletrue/' \
+			-e '/\\def\\title{GLUE}/a\
+\\pageno=\\contentspagenumber \\advance\\pageno by1\\relax' $f.tex ;;
 
 		# FIX: Metafont uses '\over' in several module names;
 		# this should appear correctly in the bookmarks, too.
-		mf ) $NEW && $SED_I $f.tex \
-			-e 's/\\def\\9/\\ifpdf\n\\sanitizecommand\\MF{Metafont}\n\\sanitizecommand\\over{\/}\n\\sanitizecommand\\langle{<}\n\\sanitizecommand\\rangle{>}\n\\fi\n\n&/' ;; # )
+		mf ) $NEW && $SED_I -e '/\\def\\MF/a\
+\\ifpdf\
+\\sanitizecommand\\MF{Metafont}\
+\\sanitizecommand\\over{\/}\
+\\sanitizecommand\\langle{<}\
+\\sanitizecommand\\rangle{>}\
+\\fi' $f.tex ;; # )
 
 		# FIX: MFT uses '\pb' in several module names;
 		# this should appear correctly in the bookmarks, too.
-		mft ) $NEW && $SED_I $f.tex \
-			-e 's/\\def\\pb.*/&\n\\ifpdf\\sanitizecommand\\pb{\|...\|}\\fi/' ;;
+		mft ) $NEW && $SED_I -e '/\\def\\pb/a\
+\\ifpdf\\sanitizecommand\\pb{\|...\|}\\fi' $f.tex ;;
 
 		# FIX: pdfTeX uses '\pdfTeX' in section names; these should
 		# appear correctly in the bookmarks, too.
-		pdftex ) $NEW && $SED_I $f.tex \
-			-e 's/\\def\\pdfeTeX{pdf\\eTeX}/&\n\\ifpdf\n\\sanitizecommand\\pdfTeX{pdfTeX}\n\\sanitizecommand\\eTeX{e-TeX}\n\\sanitizecommand\\over{\/}\n\\fi/' ;;
+		pdftex ) $NEW && $SED_I -e '/\\def\\pdfeTeX{pdf\\eTeX}/a\
+\\ifpdf\
+\\sanitizecommand\\pdfTeX{pdfTeX}\
+\\sanitizecommand\\eTeX{e-TeX}\
+\\sanitizecommand\\over{\/}\
+\\fi' $f.tex ;;
 
 		# FIX: weave uses '\max' in name of module 173; this should
 		# appear correctly in the bookmarks, too.
-		weave ) $NEW && $SED_I $f.tex \
-			-e 's/\\def\\({}/\\ifpdf\\sanitizecommand\\max{max}\\fi\n&/' ;; # )
+		weave ) $NEW && $SED_I -e '/\\def\\({}/a\
+\\ifpdf\\sanitizecommand\\max{max}\\fi' $f.tex ;; # )
 
 		# FIX: purge obsolete macros from XeTeX.
 		# FIX: XeTeX uses '\pdfTeX' from section 114, which is not
 		# changed and thus 'disappears'; repeat in preamble.
 		# FIX: apply '\sanitizecommand' for bookmarks.
-		xetex ) $SED_I $f.tex -e '/\\input xewebmac/d' \
-			-e 's/\\let\\maybe/\\def\\pdfTeX{pdf\\TeX}\n&/'
-			$NEW && $SED_I $f.tex \
-				-e 's/\\def\\pdfTeX{pdf\\TeX}/&\n\\ifpdf\\sanitizecommand\\pdfTeX{pdfTeX}\\fi/' \
-				-e 's/\\def\\eTeX/\\ifpdf\n\\sanitizecommand\\eTeX{e-TeX}\n\\sanitizecommand\\over{\/}\n\\fi\n&/' ;;
+		xetex ) $SED_I -e '/\\input xewebmac/d' \
+			-e '/\\let\\maybe/i\
+\\def\\pdfTeX{pdf\\TeX}' $f.tex
+			$NEW && $SED_I -e '/\\def\\pdfTeX/a\
+\\ifpdf\\sanitizecommand\\pdfTeX{pdfTeX}\\fi' \
+				-e '/\\def\\eTeX/a\
+\\ifpdf\
+\\sanitizecommand\\eTeX{e-TeX}\
+\\sanitizecommand\\over{\/}\
+\\fi' $f.tex ;;
 
 		# timestamp on table-of-contents page or the first page
-		hitex | mp ) $SED_I $f.tex -e 's/\\def\\topofcontents/\\datethis\n\\emergencystretch=.1\\hsize\n&/' ;;
-		common | ctangle | cweave | ctie | tie ) $SED_I $f.tex -e 's/\\def\\botofcontents/\\datethis\n&/' ;;
-		mpost | mpmath* | mpstrings | tfmin ) $SED_I $f.tex -e 's/\\def\\title{/\\datecontentspage\n\n&/' ;; # }
+		hitex | mp ) $SED_I -e '/\\def\\topofcontents/i\
+\\datethis\
+\\emergencystretch=.1\\hsize' $f.tex ;;
+		common | ctangle | cweave | ctie | tie )
+			$SED_I -e '/\\def\\botofcontents/i\
+\\datethis' $f.tex ;;
+		mpost | mpmath* | mpstrings | tfmin )
+			$SED_I -e '/\\def\\title{/i\
+\\datecontentspage\
+' $f.tex ;; # }
 	esac
 
 	# shift table-of-contents pages to the front in PDF
 	if $PDFTOCFRONT && echo $f | grep -v -q -E 'ctwill|hitex'
-	then $SED_I $f.tex \
-		-e '0,/\\N[1{]/s/\\N[1{]/\\input pdfwebtocfront\n\n&/'
+	then $SED_I -e '0,/\\N[1{]/s/\\N[1{]/\\input pdfwebtocfront\n\n&/' $f.tex
 	fi
 
 	if [ -n "$CHANGES" ] || [ twill = "$f" ]
@@ -338,27 +355,42 @@ FI
 		[ -f editorsnote.tex ] || cp $LOCALSTUFF/editorsnote.tex .
 
 		case $f in
-			mf ) $SED_I $f.tex -e 's/\\datethis/\\input editorsnote.tex\n\\def&{\\def\\startsection{\\leftline{\\sc\\today\\ at \\hours}\n  \\medskip\\editorsnote\\readchanges\\bigskip\n  \\let\\startsection=\\stsec\\stsec}}\n&/' ;;
+			mf ) $SED_I -e '/\\datethis/i\
+\\input editorsnote.tex\
+\\def\\datethis{\\def\\startsection{\\leftline{\\sc\\today\\ at \\hours}\
+  \\medskip\\editorsnote\\readchanges\\bigskip\
+  \\let\\startsection=\\stsec\\stsec}}' $f.tex ;;
 
 			# TeX and XeTeX grow significantly for TeX Live
 			# so there's enough room on the last ToC page.
-			pdftex | tex | xetex ) $SED_I $f.tex \
-				-e '/\\datethis/d' \
-				-e 's/\(\\def\\botofcontents\).*/\\input editorsnote.tex\n\1{\\hsize6.5in\\vskip 0pt plus 1filll\n  \\editorsnote\\readchanges\\medskip\\noindent\\sc\\today\\ at \\hours}/' \
-				-e 's/\\input pdfwebtocfront/&\n\n\\def\\tocpages{2}/' ;;
+			pdftex | tex | xetex ) $SED_I -e '/\\datethis/d' \
+				-e 's/\(\\def\\botofcontents\).*/\1{\\hsize6.5in\\vskip 0pt plus 1filll/' \
+				-e '/\\def\\botofcontents/i\
+\\input editorsnote.tex' \
+				-e '/\\def\\botofcontents/a\
+  \\editorsnote\\readchanges\\medskip\\noindent\\sc\\today\\ at \\hours}' \
+				-e '/\\input pdfwebtocfront/a\
+\
+\\def\\tocpages{2}' $f.tex ;;
 
-			bibtex | patgen | tangle | weave | refsort | twinx ) $SED_I $f.tex -e 's/\\date.*/\\input editorsnote\n\\def\\covernote{\\vbox{\\editorsnote\\readchanges\\par}}\n\\datecontentspage/' ;;
+			bibtex | patgen | tangle | weave | refsort | twinx )
+				$SED_I -e 's/\\date.*/\\datecontentspage/' \
+					-e '/\\datecontentspage/i\
+\\input editorsnote\
+\\def\\covernote{\\vbox{\\editorsnote\\readchanges\\par}}' $f.tex ;;
 
-			common | ctangle | cweave | ctie | tie ) $SED_I $f.tex \
-				-e 's/\\def\\covernote/\\input editorsnote.tex\n&/' \
-				-e 's/^}}/\\bigskip\\editorsnote\\readchanges\\par&/' ;;
+			common | ctangle | cweave | ctie | tie )
+				$SED_I -e '/\\def\\covernote/i\
+\\input editorsnote.tex' \
+				-e 's/^}}/\\bigskip\\editorsnote\\readchanges\\par&/' $f.tex ;;
 
-			twill ) $SED_I $f.tex \
-				-e 's/\\datecontentspage/\\input editorsnote.tex\n\\def\\covernote{\\vbox{\\editorsnote\\readchanges\\par}}\n&/' ;;
+			twill ) $SED_I -e '/\\datecontentspage/i\
+\\input editorsnote.tex\
+\\def\\covernote{\\vbox{\\editorsnote\\readchanges\\par}}' $f.tex ;;
 
-			* ) $SED_I $f.tex \
-				-e 's/\\def\\title{/\\input editorsnote.tex\n&/' \
-				-e 's/\\vbox{\\ninerm/&\\editorsnote\\readchanges\\medskip/' ;;
+			* ) $SED_I -e '/\\def\\title{/i\
+\\input editorsnote.tex' \
+				-e 's/\\vbox{\\ninerm/&\\editorsnote\\readchanges\\medskip/' $f.tex ;;
 		esac
 	fi # $CHANGES
 
